name: Artifact Demo

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Crear archivo
        run: echo "Hola desde GitHub Actions" > saludo.txt

      - name: Subir artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-archivo
          path: saludo.txt
