name: Demo Combinado

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build listo"

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint ejecutado"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests ejecutados"
