name: Demo GitHub Actions

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
